# Docker-compose configuration for production

version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django.production
        container_name: redux_saga_workshop_django
        restart: unless-stopped
        volumes:
            - "./redux_saga_workshop/app/build:/app/app/build"
            - "./redux_saga_workshop/app/webpack-stats.json:/app/app/webpack-stats.json"
            - "/var/lib/docker-nginx/files/redux_saga_workshop/media:/files/media"
            - "/var/lib/docker-nginx/files/redux_saga_workshop/assets:/files/assets"
            - "/var/log/redux_saga_workshop:/var/log/redux_saga_workshop"
        # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
        #  work.
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        command: gunicorn redux_saga_workshop.wsgi:application --workers 2 --bind :80
        depends_on:
            - redis_redux_saga_workshop
        external_links:
            - postgres-9.5:postgres

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        # Make this service no-op as we don't actually want it running but do want to use docker-compose file to define
        #  volumes etc.
        restart: "no"
        command: "true"
        volumes:
            - "./redux_saga_workshop/app:/app/app"
            - "./redux_saga_workshop/static:/app/static:ro"

    redis_redux_saga_workshop:
        image: redis:3.2.8-alpine
        restart: unless-stopped
        volumes:
            - "/var/lib/docker-redux_saga_workshop/redis:/data"

# NB: Network with this name must already exist on the server and be used by Nginx and Postgres.
networks:
    default:
        external:
            name: private
