# Docker-compose configuration for development

version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django
        ports:
            - "8000:80"
        volumes:
            - "./redux_saga_workshop:/app"
            - ".data-media:/files/media"
        environment:
            - PYTHONUNBUFFERED=0
        command: python manage.py runserver 0.0.0.0:80
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        depends_on:
            - node
            - postgres
            - redis_redux_saga_workshop

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        volumes:
            - "./redux_saga_workshop/app:/app/app"
            - "./redux_saga_workshop/static:/app/static:ro"
        command: npm run dev

    postgres:
        image: postgres:9.5
        # Comment in the following lines to connect to your Dockerized instance of Postgres from your host machine.
        # Change the host port (before colon) if you have a local instance of Postgres running on that port.
        # ports:
        #     - "5432:5432"
        volumes:
            - ".data-postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: redux_saga_workshop
            POSTGRES_PASSWORD: redux_saga_workshop

    redis_redux_saga_workshop:
        image: redis:3.2.8-alpine
        volumes:
            - ".data-redis:/data"
